on:
  push:
    branches:
    - main
    paths:
    - 2022
  workflow_dispatch:

jobs:
  Day1:
    name: "Advent of code 2022 Day 1"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2022/Day1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Setup
      run: |
        echo "Building puzzel 1"
        g++ Puzzel1.cpp -o Puzzel1.exe
        echo "Building puzzel 2"
        g++ Puzzel2.cpp -o Puzzel2.exe
        
    - name: Puzzel 1 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel1.exe

    - name: Puzzel 1 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel1.py
      
    - name: Puzzel 2 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel2.exe
  
    - name: Puzzel 2 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel2.py

  Day2:
    name: "Advent of code 2022 Day 2"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2022/Day2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Setup
      run: |
        echo "Building puzzel 1"
        g++ Puzzel1.cpp -o Puzzel1.exe
        echo "Building puzzel 2"
        g++ Puzzel2.cpp -o Puzzel2.exe
        
    - name: Puzzel 1 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel1.exe

    - name: Puzzel 1 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel1.py
      
    - name: Puzzel 2 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel2.exe
  
    - name: Puzzel 2 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel2.py

  Day3:
    name: "Advent of code 2022 Day 3"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2022/Day3
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Setup
      run: |
        echo "Building puzzel 1"
        g++ Puzzel1.cpp -o Puzzel1.exe
        echo "Building puzzel 2"
        g++ Puzzel2.cpp -o Puzzel2.exe
        
    - name: Puzzel 1 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel1.exe

    - name: Puzzel 1 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel1.py
      
    - name: Puzzel 2 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel2.exe
  
    - name: Puzzel 2 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel2.py

  Day4:
    name: "Advent of code 2022 Day 4"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2022/Day4
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Setup
      run: |
        echo "Building puzzel 1"
        g++ Puzzel1.cpp -o Puzzel1.exe
        echo "Building puzzel 2"
        g++ Puzzel2.cpp -o Puzzel2.exe
        
    - name: Puzzel 1 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel1.exe

    - name: Puzzel 1 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel1.py
      
    - name: Puzzel 2 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel2.exe
  
    - name: Puzzel 2 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel2.py

  Day5:
    name: "Advent of code 2022 Day 5"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2022/Day5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Setup
      run: |
        echo "Building puzzel 1"
        g++ Puzzel1.cpp -o Puzzel1.exe
        echo "Building puzzel 2"
        g++ Puzzel2.cpp -o Puzzel2.exe
        
    - name: Puzzel 1 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel1.exe

    - name: Puzzel 1 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel1.py
      
    - name: Puzzel 2 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel2.exe
  
    - name: Puzzel 2 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel2.py
  
  Day6:
    name: "Advent of code 2022 Day 6"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2022/Day6
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Setup
      run: |
        echo "Building puzzel 1"
        g++ Puzzel1.cpp -o Puzzel1.exe
        echo "Building puzzel 2"
        g++ Puzzel2.cpp -o Puzzel2.exe
        
    - name: Puzzel 1 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel1.exe

    - name: Puzzel 1 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel1.py
      
    - name: Puzzel 2 c++
      run: |
        echo "time c++ puzzel"
        time ./Puzzel2.exe
  
    - name: Puzzel 2 python
      run: |
        echo "time python puzzel"
        time python3 Puzzel2.py